[2022-11-13T17:12:31.338+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2022-11-13T17:12:31.356+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-09T00:00:00+00:00 [queued]>
[2022-11-13T17:12:31.358+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-13T17:12:31.359+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 7
[2022-11-13T17:12:31.360+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-13T17:12:31.382+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-09 00:00:00+00:00
[2022-11-13T17:12:31.391+0000] {standard_task_runner.py:55} INFO - Started process 3405 to run task
[2022-11-13T17:12:31.414+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v1', 'create_postgres_table', 'scheduled__2022-11-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpdaijxxii']
[2022-11-13T17:12:31.422+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask create_postgres_table
[2022-11-13T17:12:31.600+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-09T00:00:00+00:00 [running]> on host 6a6c6e07e37b
[2022-11-13T17:12:31.745+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=charlie
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-09T00:00:00+00:00
[2022-11-13T17:12:31.790+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-11-13T17:12:31.807+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-11-13T17:12:31.814+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-11-13T17:12:31.837+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221109T000000, start_date=20221113T171231, end_date=20221113T171231
[2022-11-13T17:12:31.909+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-13T17:12:31.962+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
